//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarData
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int idcliente { get; set; }
        public int id_tipo_de_documento { get; set; }
        public string nombreCliente { get; set; }
        public string apellidocliente { get; set; }
    }
}
