//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarData
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public int idfactura { get; set; }
        public int idcliente { get; set; }
        public string fecha_facturacion { get; set; }
        public decimal iva { get; set; }
        public decimal total_factura { get; set; }
    }
}
