//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarData
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int idproducto { get; set; }
        public int idcategoria { get; set; }
        public int idproveedor { get; set; }
        public string nombreProducto { get; set; }
        public int stock { get; set; }
        public string fecha_ingreso { get; set; }
        public int precioVenta { get; set; }
        public int precioCosto { get; set; }
        public string descripcionProducto { get; set; }
    }
}
