//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarData
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        public int idproveedor { get; set; }
        public int id_tipo_de_documento { get; set; }
        public string nom_proveedor { get; set; }
        public string apellido_proveedor { get; set; }
        public string telf { get; set; }
    }
}
